services:

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 50s
      retries: 30

  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - wordpress:/var/www/html
    networks:
    - inception
    depends_on:
      wordpress:
        condition: service_healthy
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 5s
      timeout: 50s
      retries: 30

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    networks:
    - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 50s
      retries: 30

  redis:
    image: redis
    container_name: redis
    networks:
    - inception
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 50s
      retries: 30

  adminer:
    image: adminer
    container_name: adminer
    networks:
    - inception
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9001"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  ftp:
    image: ftp
    container_name: ftp
    networks:
    - inception
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    ports:
    - "21:21"
    - "21000-21010:21000-21010"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "21"]
      interval: 30s
      timeout: 10s
      retries: 3

  static:
    image: static
    container_name: static
    build:
      context: requirements/bonus/static
      dockerfile: Dockerfile
    networks:
    - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  netdata:
    image: netdata
    container_name: netdata
    build: 
      context: requirements/bonus/netdata
      dockerfile: Dockerfile
      args:
        NETDATA_CLAIM_TOKEN: ${NETDATA_CLAIM_TOKEN}
        NETDATA_CLAIM_ROOMS: ${NETDATA_CLAIM_ROOMS}
        NETDATA_CLAIM_URL: ${NETDATA_CLAIM_URL}
    networks:
      - inception
    volumes:
      - wordpress:/var/lib/netdata/vol1
      - mariadb:/var/lib/netdata/vol2
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "19999:19999"
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '~/data/mariadb'

networks:
  inception:
    driver: bridge